### ISSUE TITLE
500 error GetAllWorkflowTypesWithSettings Umbraco 7.4.3, Forms 4.3.2

### ISSUE THREAD

**Issue by sbozzie** [warrenbuckley/Slack-Contour#2]
Though I notice that this package is a couple of years old, I hope you still keep an eye on this!

After installing onto Umbraco 7.4.3, when attempting to change workflow, I get the following error shown in chrome dev tools:

http://localhost:62857/umbraco/backoffice/UmbracoForms/Workflow/GetAllWorkflowTypesWithSettings Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Any guidance on whether this pacakge works, if there is an easy fix, or if I should be looking elsewhere for Forms - Slack integration would be great!

**Comment by sbozzie** [comment]
The only guidance I found was this equally old issue: http://issues.umbraco.org/issue/CON-824

**Comment by warrenbuckley** [comment]
Hello @sbozzie 
In the main core product of Umbraco Forms now has a built in Workflow provider for Slack and would recommend that is used instead of this addon package that may cause conflicts.

Thanks,
Warren

**Comment by sbozzie** [comment]
Hah, I never noticed this before - just jumped straight in installing a package! Thanks Warren!
